# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_dsa', [dirname(__file__)])
        except ImportError:
            import _dsa
            return _dsa
        if fp is not None:
            try:
                _mod = imp.load_module('_dsa', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _dsa = swig_import_helper()
    del swig_import_helper
else:
    import _dsa
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dsa.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _dsa.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _dsa.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _dsa.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _dsa.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _dsa.SwigPyIterator_equal(self, x)

    def copy(self):
        return _dsa.SwigPyIterator_copy(self)

    def next(self):
        return _dsa.SwigPyIterator_next(self)

    def __next__(self):
        return _dsa.SwigPyIterator___next__(self)

    def previous(self):
        return _dsa.SwigPyIterator_previous(self)

    def advance(self, n):
        return _dsa.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _dsa.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _dsa.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _dsa.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _dsa.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _dsa.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _dsa.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _dsa.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectord(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectord, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectord, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dsa.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dsa.vectord___nonzero__(self)

    def __bool__(self):
        return _dsa.vectord___bool__(self)

    def __len__(self):
        return _dsa.vectord___len__(self)

    def __getslice__(self, i, j):
        return _dsa.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dsa.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dsa.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dsa.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dsa.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dsa.vectord___setitem__(self, *args)

    def pop(self):
        return _dsa.vectord_pop(self)

    def append(self, x):
        return _dsa.vectord_append(self, x)

    def empty(self):
        return _dsa.vectord_empty(self)

    def size(self):
        return _dsa.vectord_size(self)

    def swap(self, v):
        return _dsa.vectord_swap(self, v)

    def begin(self):
        return _dsa.vectord_begin(self)

    def end(self):
        return _dsa.vectord_end(self)

    def rbegin(self):
        return _dsa.vectord_rbegin(self)

    def rend(self):
        return _dsa.vectord_rend(self)

    def clear(self):
        return _dsa.vectord_clear(self)

    def get_allocator(self):
        return _dsa.vectord_get_allocator(self)

    def pop_back(self):
        return _dsa.vectord_pop_back(self)

    def erase(self, *args):
        return _dsa.vectord_erase(self, *args)

    def __init__(self, *args):
        this = _dsa.new_vectord(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dsa.vectord_push_back(self, x)

    def front(self):
        return _dsa.vectord_front(self)

    def back(self):
        return _dsa.vectord_back(self)

    def assign(self, n, x):
        return _dsa.vectord_assign(self, n, x)

    def resize(self, *args):
        return _dsa.vectord_resize(self, *args)

    def insert(self, *args):
        return _dsa.vectord_insert(self, *args)

    def reserve(self, n):
        return _dsa.vectord_reserve(self, n)

    def capacity(self):
        return _dsa.vectord_capacity(self)
    __swig_destroy__ = _dsa.delete_vectord
    __del__ = lambda self: None
vectord_swigregister = _dsa.vectord_swigregister
vectord_swigregister(vectord)

class vectori(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectori, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectori, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dsa.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dsa.vectori___nonzero__(self)

    def __bool__(self):
        return _dsa.vectori___bool__(self)

    def __len__(self):
        return _dsa.vectori___len__(self)

    def __getslice__(self, i, j):
        return _dsa.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dsa.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dsa.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dsa.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dsa.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dsa.vectori___setitem__(self, *args)

    def pop(self):
        return _dsa.vectori_pop(self)

    def append(self, x):
        return _dsa.vectori_append(self, x)

    def empty(self):
        return _dsa.vectori_empty(self)

    def size(self):
        return _dsa.vectori_size(self)

    def swap(self, v):
        return _dsa.vectori_swap(self, v)

    def begin(self):
        return _dsa.vectori_begin(self)

    def end(self):
        return _dsa.vectori_end(self)

    def rbegin(self):
        return _dsa.vectori_rbegin(self)

    def rend(self):
        return _dsa.vectori_rend(self)

    def clear(self):
        return _dsa.vectori_clear(self)

    def get_allocator(self):
        return _dsa.vectori_get_allocator(self)

    def pop_back(self):
        return _dsa.vectori_pop_back(self)

    def erase(self, *args):
        return _dsa.vectori_erase(self, *args)

    def __init__(self, *args):
        this = _dsa.new_vectori(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dsa.vectori_push_back(self, x)

    def front(self):
        return _dsa.vectori_front(self)

    def back(self):
        return _dsa.vectori_back(self)

    def assign(self, n, x):
        return _dsa.vectori_assign(self, n, x)

    def resize(self, *args):
        return _dsa.vectori_resize(self, *args)

    def insert(self, *args):
        return _dsa.vectori_insert(self, *args)

    def reserve(self, n):
        return _dsa.vectori_reserve(self, n)

    def capacity(self):
        return _dsa.vectori_capacity(self)
    __swig_destroy__ = _dsa.delete_vectori
    __del__ = lambda self: None
vectori_swigregister = _dsa.vectori_swigregister
vectori_swigregister(vectori)

class vectorvectori(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorvectori, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorvectori, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dsa.vectorvectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dsa.vectorvectori___nonzero__(self)

    def __bool__(self):
        return _dsa.vectorvectori___bool__(self)

    def __len__(self):
        return _dsa.vectorvectori___len__(self)

    def __getslice__(self, i, j):
        return _dsa.vectorvectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dsa.vectorvectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dsa.vectorvectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dsa.vectorvectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dsa.vectorvectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dsa.vectorvectori___setitem__(self, *args)

    def pop(self):
        return _dsa.vectorvectori_pop(self)

    def append(self, x):
        return _dsa.vectorvectori_append(self, x)

    def empty(self):
        return _dsa.vectorvectori_empty(self)

    def size(self):
        return _dsa.vectorvectori_size(self)

    def swap(self, v):
        return _dsa.vectorvectori_swap(self, v)

    def begin(self):
        return _dsa.vectorvectori_begin(self)

    def end(self):
        return _dsa.vectorvectori_end(self)

    def rbegin(self):
        return _dsa.vectorvectori_rbegin(self)

    def rend(self):
        return _dsa.vectorvectori_rend(self)

    def clear(self):
        return _dsa.vectorvectori_clear(self)

    def get_allocator(self):
        return _dsa.vectorvectori_get_allocator(self)

    def pop_back(self):
        return _dsa.vectorvectori_pop_back(self)

    def erase(self, *args):
        return _dsa.vectorvectori_erase(self, *args)

    def __init__(self, *args):
        this = _dsa.new_vectorvectori(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dsa.vectorvectori_push_back(self, x)

    def front(self):
        return _dsa.vectorvectori_front(self)

    def back(self):
        return _dsa.vectorvectori_back(self)

    def assign(self, n, x):
        return _dsa.vectorvectori_assign(self, n, x)

    def resize(self, *args):
        return _dsa.vectorvectori_resize(self, *args)

    def insert(self, *args):
        return _dsa.vectorvectori_insert(self, *args)

    def reserve(self, n):
        return _dsa.vectorvectori_reserve(self, n)

    def capacity(self):
        return _dsa.vectorvectori_capacity(self)
    __swig_destroy__ = _dsa.delete_vectorvectori
    __del__ = lambda self: None
vectorvectori_swigregister = _dsa.vectorvectori_swigregister
vectorvectori_swigregister(vectorvectori)

class vectorvectord(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorvectord, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorvectord, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dsa.vectorvectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dsa.vectorvectord___nonzero__(self)

    def __bool__(self):
        return _dsa.vectorvectord___bool__(self)

    def __len__(self):
        return _dsa.vectorvectord___len__(self)

    def __getslice__(self, i, j):
        return _dsa.vectorvectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dsa.vectorvectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dsa.vectorvectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dsa.vectorvectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dsa.vectorvectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dsa.vectorvectord___setitem__(self, *args)

    def pop(self):
        return _dsa.vectorvectord_pop(self)

    def append(self, x):
        return _dsa.vectorvectord_append(self, x)

    def empty(self):
        return _dsa.vectorvectord_empty(self)

    def size(self):
        return _dsa.vectorvectord_size(self)

    def swap(self, v):
        return _dsa.vectorvectord_swap(self, v)

    def begin(self):
        return _dsa.vectorvectord_begin(self)

    def end(self):
        return _dsa.vectorvectord_end(self)

    def rbegin(self):
        return _dsa.vectorvectord_rbegin(self)

    def rend(self):
        return _dsa.vectorvectord_rend(self)

    def clear(self):
        return _dsa.vectorvectord_clear(self)

    def get_allocator(self):
        return _dsa.vectorvectord_get_allocator(self)

    def pop_back(self):
        return _dsa.vectorvectord_pop_back(self)

    def erase(self, *args):
        return _dsa.vectorvectord_erase(self, *args)

    def __init__(self, *args):
        this = _dsa.new_vectorvectord(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dsa.vectorvectord_push_back(self, x)

    def front(self):
        return _dsa.vectorvectord_front(self)

    def back(self):
        return _dsa.vectorvectord_back(self)

    def assign(self, n, x):
        return _dsa.vectorvectord_assign(self, n, x)

    def resize(self, *args):
        return _dsa.vectorvectord_resize(self, *args)

    def insert(self, *args):
        return _dsa.vectorvectord_insert(self, *args)

    def reserve(self, n):
        return _dsa.vectorvectord_reserve(self, n)

    def capacity(self):
        return _dsa.vectorvectord_capacity(self)
    __swig_destroy__ = _dsa.delete_vectorvectord
    __del__ = lambda self: None
vectorvectord_swigregister = _dsa.vectorvectord_swigregister
vectorvectord_swigregister(vectorvectord)


def get_test_train_dist(arg1, arg2, arg3, arg4, INOUT):
    return _dsa.get_test_train_dist(arg1, arg2, arg3, arg4, INOUT)
get_test_train_dist = _dsa.get_test_train_dist

def get_train_train_dist(arg1, arg2, INOUT):
    return _dsa.get_train_train_dist(arg1, arg2, INOUT)
get_train_train_dist = _dsa.get_train_train_dist
# This file is compatible with both classic and new-style classes.


